os: linux
language: python
cache: pip
sudo: required
services:
  - docker
env:
  global:
    - CONAN_UPLOAD: 1
    - CONAN_REFERENCE: "OpenEXR/2.2.0"
    - CONAN_USERNAME: "Mikayex"
    - CONAN_CHANNEL: "stable"
    - CONAN_TOTAL_PAGES: 8
  matrix:
    - CONAN_GCC_VERSIONS=4.6 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.6 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.6 CONAN_CURRENT_PAGE=3 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.6 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.6 CONAN_CURRENT_PAGE=5 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.6 CONAN_CURRENT_PAGE=6 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.6 CONAN_CURRENT_PAGE=7 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.6 CONAN_CURRENT_PAGE=8 CONAN_USE_DOCKER=1

    - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=3 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=5 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=6 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=7 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=8 CONAN_USE_DOCKER=1

    - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=3 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=5 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=6 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=7 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=8 CONAN_USE_DOCKER=1

    - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=3 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=5 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=6 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=7 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=8 CONAN_USE_DOCKER=1

    - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=3 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=5 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=6 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=7 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=8 CONAN_USE_DOCKER=1

    - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=3 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=5 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=6 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=7 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=8 CONAN_USE_DOCKER=1

    - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=3 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=5 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=6 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=7 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=8 CONAN_USE_DOCKER=1

matrix:
   include:
       - os: osx
         osx_image: xcode8 # apple-clang 8
         language: generic
         env: CONAN_CURRENT_PAGE=1
       - os: osx
         osx_image: xcode8 # apple-clang 8
         language: generic
         env: CONAN_CURRENT_PAGE=2
       - os: osx
         osx_image: xcode8 # apple-clang 8
         language: generic
         env: CONAN_CURRENT_PAGE=3
       - os: osx
         osx_image: xcode8 # apple-clang 8
         language: generic
         env: CONAN_CURRENT_PAGE=4
       - os: osx
         osx_image: xcode8 # apple-clang 8
         language: generic
         env: CONAN_CURRENT_PAGE=5
       - os: osx
         osx_image: xcode8 # apple-clang 8
         language: generic
         env: CONAN_CURRENT_PAGE=6
       - os: osx
         osx_image: xcode8 # apple-clang 8
         language: generic
         env: CONAN_CURRENT_PAGE=7
       - os: osx
         osx_image: xcode8 # apple-clang 8
         language: generic
         env: CONAN_CURRENT_PAGE=8

       - os: osx
         osx_image: xcode7.3 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=1
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=2
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=3
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=4
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=5
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=6
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=7
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=8

       - os: osx
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=1
       - os: osx
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=2
       - os: osx
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=3
       - os: osx
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=4
       - os: osx
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=5
       - os: osx
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=6
       - os: osx
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=7
       - os: osx
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=8

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
